(()=>{
"use strict";
const PILOT={lat:43.2858,lon:5.4140};
const CFG={laneWidthM:3.2,maxRoadDistanceM:45,queryRadiusKm:1.25,reloadAfterM:700,offRouteM:42,rerouteCooldownMs:12000,overpass:["https://overpass-api.de/api/interpreter","https://overpass.kumi.systems/api/interpreter","https://overpass.nchc.org.tw/api/interpreter"],router:"https://router.project-osrm.org/route/v1/driving"};
const S={map:null,roads:[],signals:[],environment:[],gps:null,rawGps:null,heading:0,gpsWatch:null,areaCenter:null,environmentCenter:null,userMarker:null,accuracyCircle:null,destinationMarker:null,destination:null,route:null,routeLayer:null,routeCoords:[],routeLengthM:0,routeManeuvers:[],view:"map",demo:false,demoT:0,demoTimer:null,visionStream:null,lastMatch:null,lastLane:null,lastNav:null,lastRerouteAt:0,offRouteHits:0,arrived:false};
const $=id=>document.getElementById(id),clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI,angleDiff=(a,b)=>Math.abs(((a-b+540)%360)-180),pipe=v=>typeof v==="string"?v.split("|").map(x=>x.trim()):[],positiveInt=v=>{const n=parseInt(v,10);return Number.isFinite(n)&&n>0?n:0};
function setStatus(t){$("status").textContent=t}
function roadName(r){const m={motorway:"Autoroute",trunk:"Voie rapide",primary:"Axe principal",secondary:"Route secondaire",tertiary:"Route tertiaire",residential:"Rue résidentielle",service:"Voie de service",unclassified:"Route",living_street:"Zone de rencontre"};return r?.tags?.name||r?.tags?.ref||m[r?.tags?.highway]||"Route sans nom"}
function haversineM(a,b){const R=6371000,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(Math.max(0,1-q)))}
function bearing(a,b){const p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lon-a.lon),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(deg(Math.atan2(y,x))+360)%360}
function pointToSegment(p,a,b){const mx=111320*Math.cos(rad(p.lat)),my=110540,px=(p.lon-a.lon)*mx,py=(p.lat-a.lat)*my,bx=(b.lon-a.lon)*mx,by=(b.lat-a.lat)*my,l2=bx*bx+by*by,t=l2?clamp((px*bx+py*by)/l2,0,1):0,x=bx*t,y=by*t;return{distance:Math.hypot(px-x,py-y),t,nearest:{lat:a.lat+y/my,lon:a.lon+x/mx}}}
function bbox(lat,lon,km){const dLat=km/111,dLon=km/(111*Math.cos(rad(lat)));return`${(lat-dLat).toFixed(6)},${(lon-dLon).toFixed(6)},${(lat+dLat).toFixed(6)},${(lon+dLon).toFixed(6)}`}
function laneCount(tags,dir){const v=dir==="forward"?tags["lanes:forward"]:tags["lanes:backward"];return positiveInt(v||tags.lanes)}
function laneTurns(tags,dir){const a=pipe(tags[`turn:lanes:${dir}`]||tags["turn:lanes"]);return a.length?a:Array.from({length:Math.max(1,laneCount(tags,dir))},()=>"through")}
function laneChanges(tags,dir){return pipe(tags[`change:lanes:${dir}`]||tags["change:lanes"])}
function maxspeedKph(tags){const raw=String(tags?.maxspeed||"").trim().toLowerCase();if(!raw)return null;const n=parseFloat(raw);if(Number.isFinite(n))return Math.round(raw.includes("mph")?n*1.60934:n);return({"fr:urban":50,"fr:rural":80,"fr:trunk":110,"fr:motorway":130})[raw]||null}
function updateSpeedLimit(match,pos){const el=$("limitBadge"),limit=match?maxspeedKph(match.road.tags):null;if(!limit){el.classList.add("hidden");el.classList.remove("alert");return}el.textContent=String(limit);el.classList.remove("hidden");el.classList.toggle("alert",pos.speedMps*3.6>limit+5)}
function turnGlyph(raw){const vals=String(raw||"through").split(";").map(v=>v.trim());const glyph=v=>v.includes("uturn")||v.includes("reverse")?"↶":v.includes("left")?"↰":v.includes("right")?"↱":"↑";return [...new Set(vals.map(glyph))].join("")}
function updateJunctionAssist(lane,nav){const panel=$("junctionAssist");if(!nav||nav.arrived||!Number.isFinite(nav.distance)||nav.distance>500){panel.classList.add("hidden");return}panel.classList.remove("hidden");$("junctionText").textContent=`${nav.instruction} · ${Math.max(0,Math.round(nav.distance))} m`;const lanes=$("junctionLanes");if(lane.hasTurnLanes&&lane.turns.length){const good=compatibleLanes(lane,nav.turn);lanes.innerHTML=lane.turns.map((t,i)=>`<span class="${good.includes(i+1)?"recommended":""}">${turnGlyph(t)}</span>`).join("")}else{lanes.innerHTML='<small>Voies directionnelles non renseignées sur cette section</small>'}}
function envHeight(tags){const h=parseFloat(String(tags?.height||"").replace(",",".") );if(Number.isFinite(h)&&h>1)return clamp(h,3,60);const levels=parseFloat(tags?.["building:levels"]);return clamp(Number.isFinite(levels)&&levels>0?levels*3.1:10,3,45)}
function envKind(tags){if(tags?.building)return"building";if(tags?.natural==="tree")return"tree";if(tags?.highway==="street_lamp")return"lamp";if(tags?.shop||tags?.amenity)return"poi";return"other"}
function environmentObject(e){const loc=e.type==="node"?{lat:e.lat,lon:e.lon}:e.center;if(!loc||!Number.isFinite(loc.lat)||!Number.isFinite(loc.lon))return null;const tags=e.tags||{},kind=envKind(tags);return{id:String(e.id),kind,lat:loc.lat,lon:loc.lon,height:envHeight(tags),name:tags.name||tags.brand||tags.shop||tags.amenity||"",tags}}
async function loadEnvironmentData(lat,lon){const b=bbox(lat,lon,.42),q=`[out:json][timeout:25];(way["building"](${b});node["natural"="tree"](${b});node["highway"="street_lamp"](${b});node["amenity"](${b});node["shop"](${b}););out center tags;`;try{const data=await fetchOverpass(q),objects=[];for(const e of data.elements||[]){const o=environmentObject(e);if(o)objects.push(o)}objects.sort((a,b)=>haversineM({lat,lon},a)-haversineM({lat,lon},b));S.environment=objects.slice(0,650);S.environmentCenter={lat,lon};try{localStorage.setItem("mdEnvCacheV1",JSON.stringify({lat,lon,time:Date.now(),objects:S.environment}))}catch(_){}if($("envBadge"))$("envBadge").textContent=`URBAIN ${S.environment.length}`}catch(e){let used=false;try{const cache=JSON.parse(localStorage.getItem("mdEnvCacheV1")||"null");if(cache&&Date.now()-cache.time<86400000&&haversineM({lat,lon},cache)<2500){S.environment=cache.objects||[];S.environmentCenter={lat:cache.lat,lon:cache.lon};used=true}}catch(_){}if($("envBadge"))$("envBadge").textContent=used?`CACHE ${S.environment.length}`:"URBAIN —"}}
function signedAngle(from,to){return((to-from+540)%360)-180}
function visibleEnvironment(pos,heading,maxM=260){if(!pos||!S.environment.length)return[];const out=[];for(const o of S.environment){const d=haversineM(pos,o);if(d<5||d>maxM)continue;const a=signedAngle(heading,bearing(pos,o)),forward=Math.cos(rad(a))*d,side=Math.sin(rad(a))*d;if(forward<5||forward>maxM||Math.abs(side)>130)continue;out.push({...o,distance:d,forward,side})}return out.sort((a,b)=>b.forward-a.forward).slice(0,90)}
function openStreetReference(){if(!S.gps){setStatus("Active le GPS avant d’ouvrir la vue 360°.");return}const rb=S.lastMatch?(travelDirection(S.lastMatch,S.gps)==="forward"?S.lastMatch.roadBearing:(S.lastMatch.roadBearing+180)%360):0,heading=Math.round(S.gps.speedMps>1.5&&Number.isFinite(S.heading)?S.heading:rb),url=`https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${encodeURIComponent(S.gps.lat+","+S.gps.lon)}&heading=${heading}&pitch=0&fov=85`;window.open(url,"_blank","noopener")}
function initMap(){S.map=L.map("map",{zoomControl:false,preferCanvas:true,inertia:true}).setView([PILOT.lat,PILOT.lon],15);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors",crossOrigin:true}).addTo(S.map);S.map.on("click",e=>{if(!S.gps){setStatus("Active le GPS avant de choisir une destination.");return}setDestination(e.latlng.lat,e.latlng.lng)})}
async function fetchOverpass(q){let last;for(const ep of CFG.overpass){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),13000);try{const r=await fetch(ep,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"data="+encodeURIComponent(q),signal:ctrl.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}catch(e){last=e}finally{clearTimeout(timer)}}throw last||Error("Overpass indisponible")}
async function loadRoadData(lat,lon){setStatus("Chargement des routes autour de toi…");const b=bbox(lat,lon,CFG.queryRadiusKm),q=`[out:json][timeout:30];(way["highway"]["highway"!~"footway|path|steps|pedestrian|cycleway"](${b});node["highway"="traffic_signals"](${b}););out geom tags;`;try{const data=await fetchOverpass(q),roads=[],signals=[];for(const e of data.elements||[]){if(e.type==="way"&&e.tags?.highway&&e.geometry?.length>1)roads.push({id:String(e.id),tags:e.tags,coords:e.geometry.map(p=>({lat:p.lat,lon:p.lon}))});else if(e.type==="node"&&e.tags?.highway==="traffic_signals")signals.push({id:String(e.id),lat:e.lat,lon:e.lon,tags:e.tags})}S.roads=roads;S.signals=signals;S.areaCenter={lat,lon};try{localStorage.setItem("mdRoadCacheV1",JSON.stringify({lat,lon,time:Date.now(),roads,signals}))}catch(_){}loadEnvironmentData(lat,lon);setStatus(`${roads.length} routes · ${signals.length} feux cartographiés`)}catch(e){let used=false;try{const cache=JSON.parse(localStorage.getItem("mdRoadCacheV1")||"null");if(cache&&Date.now()-cache.time<86400000&&haversineM({lat,lon},cache)<3000){S.roads=cache.roads||[];S.signals=cache.signals||[];S.areaCenter={lat:cache.lat,lon:cache.lon};used=true;setStatus(`Mode cache local · ${S.roads.length} routes`)}}catch(_){}if(!used)setStatus("Données OSM indisponibles — GPS toujours actif")}}
function nearestRoad(pos){let best=null;for(const road of S.roads){for(let i=0;i<road.coords.length-1;i++){const a=road.coords[i],b=road.coords[i+1],s=pointToSegment(pos,a,b);if(s.distance>CFG.maxRoadDistanceM)continue;const rb=bearing(a,b),pen=pos.speedMps>2&&Number.isFinite(pos.heading)?angleDiff(pos.heading,rb)/15:0,score=s.distance+pen;if(!best||score<best.score)best={road,distance:s.distance,nearest:s.nearest,roadBearing:rb,score}}}return best}
function travelDirection(m,pos){if(["yes","1","true"].includes(m.road.tags.oneway))return"forward";if(pos.speedMps<1.5||!Number.isFinite(pos.heading))return"forward";return angleDiff(pos.heading,m.roadBearing)<=90?"forward":"backward"}
function signedLateralM(pos,nearest,rb){const d=haversineM(pos,nearest),b=bearing(nearest,pos);return Math.sin(rad(((b-rb+540)%360)-180))*d}
function estimateLane(m,pos){const dir=travelDirection(m,pos),total=laneCount(m.road.tags,dir),rb=dir==="forward"?m.roadBearing:(m.roadBearing+180)%360,acc=Number.isFinite(pos.accuracy)?pos.accuracy:999,headErr=Number.isFinite(pos.heading)?angleDiff(pos.heading,rb):90,confidence=clamp(Math.round(100-Math.min(m.distance,40)*1.4-Math.min(acc,40)*2.35-Math.min(headErr,90)*.25),0,100),hasTurnLanes=Boolean(m.road.tags[`turn:lanes:${dir}`]||m.road.tags["turn:lanes"]),base={dir,total,confidence,hasTurnLanes,turns:laneTurns(m.road.tags,dir),changes:laneChanges(m.road.tags,dir)};if(!total)return{...base,index:null,reason:"Nombre de voies absent dans OSM"};if(acc>5.5||confidence<62)return{...base,index:null,reason:`GPS ±${Math.round(acc)} m : pas assez précis pour une voie`};const off=signedLateralM(pos,m.nearest,rb),ratio=clamp(off/(total*CFG.laneWidthM),-.499,.499),index=clamp(Math.floor((ratio+.5)*total)+1,1,total);return{...base,index,reason:"Estimation GPS + axe OSM"}}
function smoothGps(raw){if(!S.gps)return raw;const acc=clamp(raw.accuracy,3,40),alpha=raw.speedMps>8?.5:raw.speedMps>2?.35:.22,weight=clamp(alpha*(12/acc),.12,.65);const sm={...raw,lat:S.gps.lat+(raw.lat-S.gps.lat)*weight,lon:S.gps.lon+(raw.lon-S.gps.lon)*weight};if(Number.isFinite(raw.heading)&&raw.speedMps>1.5){const a=rad(S.gps.heading||raw.heading),b=rad(raw.heading),x=Math.cos(a)*.65+Math.cos(b)*.35,y=Math.sin(a)*.65+Math.sin(b)*.35;sm.heading=(deg(Math.atan2(y,x))+360)%360}else sm.heading=S.gps.heading||raw.heading||0;return sm}
function updateUserMarker(pos){const ll=[pos.lat,pos.lon];if(!S.userMarker){const icon=L.divIcon({className:"",html:'<div class="user-dot"></div>',iconSize:[18,18],iconAnchor:[9,9]});S.userMarker=L.marker(ll,{icon,zIndexOffset:1000}).addTo(S.map);S.accuracyCircle=L.circle(ll,{radius:pos.accuracy||10,weight:1,color:"#1d79ff",fillColor:"#1d79ff",fillOpacity:.08}).addTo(S.map)}else{S.userMarker.setLatLng(ll);S.accuracyCircle.setLatLng(ll).setRadius(pos.accuracy||10)}if(S.view==="map")S.map.setView(ll,17,{animate:true})}
function routeProjection(pos){if(!S.routeCoords.length)return null;let best=null,cum=0;for(let i=0;i<S.routeCoords.length-1;i++){const a=S.routeCoords[i],b=S.routeCoords[i+1],segLen=haversineM(a,b),p=pointToSegment(pos,a,b);if(!best||p.distance<best.distance)best={distance:p.distance,index:i,t:p.t,along:cum+segLen*p.t,nearest:p.nearest};cum+=segLen}if(best){best.total=cum;best.remaining=Math.max(0,cum-best.along);best.progress=cum?best.along/cum:0}return best}
function buildRouteManeuvers(){S.routeManeuvers=[];const steps=S.route?.legs?.[0]?.steps||[];for(const step of steps){const loc=step.maneuver?.location;if(!loc)continue;const point={lat:loc[1],lon:loc[0]},proj=routeProjection(point);if(!proj)continue;S.routeManeuvers.push({step,along:proj.along,point,type:step.maneuver?.type||"",modifier:step.maneuver?.modifier||"straight"})}S.routeManeuvers.sort((a,b)=>a.along-b.along)}
function maneuverTurn(m){const mod=m?.modifier||"straight",type=m?.type||"";if(type.includes("roundabout")||type==="rotary")return"roundabout";if(mod.includes("left"))return"left";if(mod.includes("right"))return"right";if(mod==="uturn")return"uturn";return"through"}
function nextInstruction(pos){const proj=routeProjection(pos);if(!proj)return{instruction:"Suivre l’itinéraire",detail:"",turn:"through",distance:null};const dest=S.destination?haversineM(pos,S.destination):Infinity;if(proj.remaining<35||dest<35)return{instruction:"Destination atteinte",detail:"Tu es arrivé",turn:"through",distance:0,remaining:0,progress:1,offRoute:proj.distance,arrived:true};let candidate=null;for(const m of S.routeManeuvers){if(m.type==="depart")continue;if(m.along>=proj.along-12){candidate=m;break}}if(!candidate)return{instruction:"Continue jusqu’à destination",detail:`${Math.round(proj.remaining)} m restants`,turn:"through",distance:proj.remaining,remaining:proj.remaining,progress:proj.progress,offRoute:proj.distance};const distance=Math.max(0,candidate.along-proj.along),turn=maneuverTurn(candidate),exit=candidate.step.maneuver?.exit;let instruction={left:"Tourne à gauche",right:"Tourne à droite",uturn:"Demi-tour",through:"Continue tout droit",roundabout:"Prends le rond-point"}[turn];if(turn==="roundabout"&&exit)instruction+=` · sortie ${exit}`;return{instruction,detail:`Dans ~${Math.round(distance)} m · ${candidate.step.name||"prochaine voie"}`,turn,distance,remaining:proj.remaining,progress:proj.progress,offRoute:proj.distance,arrived:false}}
function compatibleLanes(lane,turn){if(!lane.total)return[];const desired=turn||"through",out=[];lane.turns.forEach((raw,i)=>{const vals=raw.split(";").map(v=>v.trim());if(vals.includes(desired)||(desired==="through"&&(vals.includes("through")||vals.includes("straight"))))out.push(i+1)});return out}
function recommendedLane(lane,turn){if(turn&&turn!=="through"&&!lane.hasTurnLanes)return null;const c=compatibleLanes(lane,turn);if(!c.length)return turn==="through"?(lane.index||null):null;if(!lane.index)return c[0];return c.reduce((a,b)=>Math.abs(b-lane.index)<Math.abs(a-lane.index)?b:a)}
function adviceText(lane,nav){if(!nav){return lane.index?`🟢 VOIE PROBABLE ${lane.index}/${lane.total}`:(lane.total?`🟡 ${lane.total} VOIES · POSITION INCONNUE`:"Voies non renseignées")}if(nav.arrived)return"🏁 DESTINATION ATTEINTE";if(nav.turn!=="through"&&!lane.hasTurnLanes){const dir=nav.turn==="left"?"À GAUCHE":nav.turn==="right"?"À DROITE":nav.turn==="roundabout"?"AU ROND-POINT":"POUR LA MANŒUVRE";return `↪ PRÉPARE-TOI ${dir} · VOIE NON CARTOGRAPHIÉE`}const rec=recommendedLane(lane,nav.turn),d=nav.distance??9999;if(!rec)return lane.total?`🟡 ${lane.total} VOIES · POSITION INCONNUE`:"Voies non renseignées";const urgency=d>350?"PRÉPARE":d>120?"REJOINS":"MAINTENANT";if(lane.index&&rec===lane.index)return d<120?`🟢 RESTE VOIE ${lane.index}/${lane.total}`:`🟢 BONNE VOIE ${lane.index}/${lane.total}`;return lane.index?`➡️ ${urgency} VOIE ${rec}/${lane.total}`:`➡️ VOIE CONSEILLÉE ${rec}/${lane.total}`}
function relevantSignal(pos,m){let best=null;const heading=m?(travelDirection(m,pos)==="forward"?m.roadBearing:(m.roadBearing+180)%360):pos.heading;for(const s of S.signals){const d=haversineM(pos,s);if(d>450)continue;const a=angleDiff(heading,bearing(pos,s));if(a>65)continue;const score=d+a*2;if(!best||score<best.score)best={...s,distance:d,score}}return best}
async function maybeReroute(pos,nav){if(!S.route||!S.destination||!nav)return;if((nav.offRoute||0)>CFG.offRouteM)S.offRouteHits++;else S.offRouteHits=0;if(S.offRouteHits<3)return;const now=Date.now();if(now-S.lastRerouteAt<CFG.rerouteCooldownMs)return;S.lastRerouteAt=now;S.offRouteHits=0;setStatus("Hors itinéraire · recalcul automatique…");await calculateRoute(S.destination.lat,S.destination.lon,true)}
function updateUi(pos){$("speed").textContent=Math.round(pos.speedMps*3.6);const m=nearestRoad(pos);S.lastMatch=m;if(!m){$("road").textContent="—";$("lane").textContent="—";$("confidence").textContent="—";$("advice").textContent="Route à confirmer";$("source").textContent="SOURCE GPS";updateSpeedLimit(null,pos);$("junctionAssist").classList.add("hidden");return}const lane=estimateLane(m,pos),nav=S.route?nextInstruction(pos):null,sig=relevantSignal(pos,m);S.lastLane=lane;S.lastNav=nav;updateSpeedLimit(m,pos);updateJunctionAssist(lane,nav);$("road").textContent=roadName(m.road);$("lane").textContent=lane.index?`${lane.index}/${lane.total}`:(lane.total?`?/${lane.total}`:"—");$("confidence").textContent=`${lane.confidence}%`;$("signal").textContent=sig?`${Math.round(sig.distance)} m`:"—";$("source").textContent=lane.index?"ESTIMATION":"PAS ASSEZ PRÉCIS";if(nav){$("instruction").textContent=nav.instruction;$("detail").textContent=`${nav.detail} · ${lane.reason}`;$("advice").textContent=adviceText(lane,nav);if(nav.arrived){S.arrived=true;$("progressWrap").classList.remove("hidden");$("progressBar").style.width="100%";$("routeMeta").textContent="Arrivée";setStatus("Destination atteinte")}else if(Number.isFinite(nav.progress)){S.arrived=false;$("progressWrap").classList.remove("hidden");$("progressBar").style.width=`${clamp(nav.progress*100,0,100)}%`;const rem=nav.remaining??S.route.distance;$("routeMeta").textContent=`${(rem/1000).toFixed(1)} km restants · ~${Math.max(1,Math.round(rem/Math.max(6,pos.speedMps||10)/60))} min`}}else{$("instruction").textContent=roadName(m.road);$("detail").textContent=lane.reason;$("advice").textContent=adviceText(lane,null)}draw3D({lane:lane.index||2,total:lane.total||3,recommended:nav?recommendedLane(lane,nav.turn)||(lane.index||2):(lane.index||2),turn:nav?.turn||"through",distance:nav?.distance,arrived:nav?.arrived,signal:sig});maybeReroute(pos,nav)}
async function startGps(){if(!window.isSecureContext){setStatus("GPS : ouvre bien l’adresse HTTPS GitHub Pages.");return}if(!navigator.geolocation){setStatus("GPS non disponible.");return}$("permission")?.remove();$("gpsBtn").classList.add("active");$("gpsBtn").querySelector("span").textContent="Actif";if(S.gpsWatch!==null)navigator.geolocation.clearWatch(S.gpsWatch);S.gpsWatch=navigator.geolocation.watchPosition(async p=>{const c=p.coords,raw={lat:c.latitude,lon:c.longitude,speedMps:Math.max(0,Number.isFinite(c.speed)?c.speed:0),heading:Number.isFinite(c.heading)&&c.heading>=0?c.heading:S.heading,accuracy:Number.isFinite(c.accuracy)?c.accuracy:999};S.rawGps=raw;S.gps=smoothGps(raw);S.heading=S.gps.heading;updateUserMarker(S.gps);if(!S.areaCenter||haversineM(S.gps,S.areaCenter)>CFG.reloadAfterM)await loadRoadData(S.gps.lat,S.gps.lon);updateUi(S.gps);setStatus(`GPS ±${Math.round(raw.accuracy)} m · ${S.roads.length} routes`)},e=>setStatus("GPS : "+e.message),{enableHighAccuracy:true,maximumAge:500,timeout:15000})}
async function calculateRoute(lat,lon,isReroute=false){if(!S.gps){setStatus("Active le GPS d’abord.");return}S.destination={lat,lon};$("routeTitle").textContent=`Destination ${lat.toFixed(5)}, ${lon.toFixed(5)}`;$("clearRoute").hidden=false;if(!isReroute&&S.destinationMarker)S.map.removeLayer(S.destinationMarker);if(!isReroute){const icon=L.divIcon({className:"",html:'<div class="destination-dot"></div>',iconSize:[16,16],iconAnchor:[8,16]});S.destinationMarker=L.marker([lat,lon],{icon}).addTo(S.map)}setStatus(isReroute?"Recalcul en cours…":"Calcul de l’itinéraire…");try{const o=S.gps,url=`${CFG.router}/${o.lon},${o.lat};${lon},${lat}?overview=full&geometries=geojson&steps=true`,r=await fetch(url);if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();if(d.code!=="Ok"||!d.routes?.length)throw Error("Aucun itinéraire");S.route=d.routes[0];S.routeCoords=S.route.geometry.coordinates.map(c=>({lat:c[1],lon:c[0]}));S.routeLengthM=S.route.distance;buildRouteManeuvers();S.arrived=false;if(S.routeLayer)S.map.removeLayer(S.routeLayer);S.routeLayer=L.polyline(S.routeCoords.map(p=>[p.lat,p.lon]),{color:"#fff",weight:7,opacity:.93,className:"route-line"}).addTo(S.map);if(!isReroute)S.map.fitBounds(S.routeLayer.getBounds(),{padding:[45,45]});$("routeMeta").textContent=`${(S.route.distance/1000).toFixed(1)} km · ~${Math.max(1,Math.round(S.route.duration/60))} min`;$("progressWrap").classList.remove("hidden");setStatus(isReroute?"Nouvel itinéraire chargé":"Itinéraire chargé · passe en 3D quand tu veux");updateUi(S.gps)}catch(e){setStatus("Itinéraire indisponible : "+e.message)}}
function setDestination(lat,lon){calculateRoute(lat,lon,false)}
function clearRoute(){S.route=null;S.routeCoords=[];S.routeManeuvers=[];S.destination=null;S.arrived=false;S.offRouteHits=0;if(S.routeLayer){S.map.removeLayer(S.routeLayer);S.routeLayer=null}if(S.destinationMarker){S.map.removeLayer(S.destinationMarker);S.destinationMarker=null}$("routeTitle").textContent="Touchez la carte pour choisir une destination";$("routeMeta").textContent="Active d’abord le GPS.";$("clearRoute").hidden=true;$("progressWrap").classList.add("hidden");$("progressBar").style.width="0%";$("junctionAssist").classList.add("hidden");if(S.gps)updateUi(S.gps)}
function setView(v){S.view=v;$("map").style.display=v==="map"?"block":"none";$("drive").style.display=v==="drive"?"block":"none";$("car").style.display=v==="drive"?"block":"none";$("mapBtn").classList.toggle("active",v==="map");$("driveBtn").classList.toggle("active",v==="drive");$("modeLabel").textContent=`BETA 6.1 · ${v==="map"?"CARTE RÉELLE":"NAVIGATION 3D"}`;if(v==="map")setTimeout(()=>S.map.invalidateSize(),80);else draw3D({lane:S.lastLane?.index||2,total:S.lastLane?.total||3,recommended:S.lastNav?recommendedLane(S.lastLane,S.lastNav.turn)||(S.lastLane?.index||2):(S.lastLane?.index||2),turn:S.lastNav?.turn||"through",distance:S.lastNav?.distance,signal:S.gps?relevantSignal(S.gps,S.lastMatch):null})}
async function toggleVision(){if(S.visionStream){closeVision();return}if(!navigator.mediaDevices?.getUserMedia){setStatus("Caméra non disponible.");return}try{S.visionStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});$("camera").srcObject=S.visionStream;$("visionPanel").classList.remove("hidden");setStatus("Vision locale active · aucune image envoyée")}catch(e){setStatus("Caméra : autorisation refusée ou indisponible.")}}
function closeVision(){S.visionStream?.getTracks().forEach(t=>t.stop());S.visionStream=null;$("visionPanel").classList.add("hidden")}
function startDemo(){if(S.demo){S.demo=false;clearInterval(S.demoTimer);S.demoTimer=null;$("demoBtn").querySelector("span").textContent="Démo";setStatus(S.gps?"GPS réel":"Démo arrêtée");if(S.gps)updateUi(S.gps);return}S.demo=true;S.demoT=0;setView("drive");$("demoBtn").querySelector("span").textContent="Pause";$("source").textContent="SIMULATION";setStatus("MODE DÉMO — données simulées");S.demoTimer=setInterval(()=>{S.demoT+=.1;if(S.demoT>24)S.demoT=0;const t=S.demoT,change=t>7&&t<15,lane=t>=15?3:2,recommended=change?3:lane,turn=t>7?"right":"through",signal=18-(t%18),distance=Math.max(0,460-t*17),progress=clamp(t/24,0,1);$("speed").textContent=Math.round(48+Math.sin(t*.8)*2);$("lane").textContent=`${lane}/3`;$("confidence").textContent="96%";$("road").textContent="Avenue pilote";$("signal").textContent=`${Math.ceil(signal)} s*`;$("limitBadge").textContent="50";$("limitBadge").classList.remove("hidden");$("instruction").textContent=change?"Change de voie":turn==="right"?"Tourne à droite":"Continue tout droit";$("detail").textContent=`Dans ${Math.round(distance)} m · feu SIMULÉ`;$("advice").textContent=recommended===lane?`🟢 RESTE VOIE ${lane}/3`:`➡️ ${distance>120?"REJOINS":"MAINTENANT"} VOIE ${recommended}/3`;$("routeTitle").textContent="Itinéraire de démonstration";$("routeMeta").textContent=`${Math.max(0,(3.2*(1-progress))).toFixed(1)} km restants`;$("progressWrap").classList.remove("hidden");$("progressBar").style.width=`${progress*100}%`;updateJunctionAssist({total:3,index:lane,hasTurnLanes:true,turns:["through","through","right"]},{instruction:turn==="right"?"Tourne à droite":"Continue tout droit",turn,distance,arrived:false});draw3D({lane,total:3,recommended,turn,signal,distance,demo:true})},100)}
function poly(c,p,f){c.beginPath();p.forEach((x,i)=>i?c.lineTo(x[0],x[1]):c.moveTo(x[0],x[1]));c.closePath();c.fillStyle=f;c.fill()}
function line(c,p,col,w){c.beginPath();p.forEach((x,i)=>i?c.lineTo(x[0],x[1]):c.moveTo(x[0],x[1]));c.strokeStyle=col;c.lineWidth=w;c.stroke()}
function arrow(c,x,y,on,turn){c.save();c.strokeStyle=on?"#fff":"#c5cdd1";c.lineWidth=on?5:3;c.lineCap="round";c.lineJoin="round";c.beginPath();c.moveTo(x,y+20);c.lineTo(x,y-16);if(on&&turn==="right"){c.quadraticCurveTo(x,y-27,x+18,y-28);c.moveTo(x+18,y-28);c.lineTo(x+10,y-35);c.moveTo(x+18,y-28);c.lineTo(x+10,y-21)}else if(on&&turn==="left"){c.quadraticCurveTo(x,y-27,x-18,y-28);c.moveTo(x-18,y-28);c.lineTo(x-10,y-35);c.moveTo(x-18,y-28);c.lineTo(x-10,y-21)}else{c.moveTo(x,y-16);c.lineTo(x-8,y-6);c.moveTo(x,y-16);c.lineTo(x+8,y-6)}c.stroke();c.restore()}
function perspectiveEnvPoint(side,forward,w,h,hz){if(forward<=4||forward>270)return null;const depth=clamp(1-forward/285,0,1),y=hz+(h-hz)*Math.pow(depth,1.55)*.82,x=w/2+side*(w*.78)/(forward+42),scale=clamp(92/(forward+28),.18,1.7);return{x,y,scale}}
function drawEnvironment(c,w,h,hz,heading){const pos=S.demo?null:S.gps;if(!pos||!S.environment.length){
  const blocks=[[-.48,.11,.16,.24],[-.30,.09,.13,.18],[-.14,.08,.11,.14],[.14,.08,.11,.15],[.30,.10,.14,.20],[.48,.12,.16,.26]];
  for(const [sx,sw,sh,depth] of blocks){
    const bw=w*sw,bh=h*sh,x=w/2+w*sx-bw/2,y=hz;
    c.fillStyle=depth>.2?"#46545c":"#38464e";c.fillRect(x,y-bh,bw,bh);
    c.fillStyle="#9aa8ae";
    for(let r=0;r<3;r++)for(let col=0;col<2;col++)c.fillRect(x+bw*.18+col*bw*.38,y-bh*.78+r*bh*.23,Math.max(2,bw*.10),Math.max(2,bh*.07));
  }
  for(let i=0;i<6;i++){const side=i<3?-1:1,k=i%3,x=w/2+side*(w*.18+k*w*.11),y=hz+28+k*18;c.strokeStyle="#68747a";c.lineWidth=2;c.beginPath();c.moveTo(x,y);c.lineTo(x,y-28-k*3);c.stroke();c.fillStyle="#dbe2c1";c.beginPath();c.arc(x,y-30-k*3,3,0,Math.PI*2);c.fill()}
  for(let i=0;i<4;i++){const side=i<2?-1:1,k=i%2,x=w/2+side*(w*.27+k*w*.13),y=hz+55+k*35;c.strokeStyle="#314139";c.lineWidth=3;c.beginPath();c.moveTo(x,y);c.lineTo(x,y-20);c.stroke();c.fillStyle="#42604e";c.beginPath();c.arc(x,y-28,10,0,Math.PI*2);c.fill()}
  return
}const objs=visibleEnvironment(pos,heading);let labels=0;for(const o of objs){const p=perspectiveEnvPoint(o.side,o.forward,w,h,hz);if(!p)continue;if(o.kind==="building"){const bw=clamp((18+Math.min(16,o.height*.25))*p.scale,6,110),bh=clamp((16+o.height*2.0)*p.scale,7,h*.42);c.fillStyle=o.forward<70?"#45535b":"#35434b";c.fillRect(p.x-bw/2,p.y-bh,bw,bh);c.fillStyle="#26343b";c.beginPath();c.moveTo(p.x-bw/2,p.y-bh);c.lineTo(p.x-bw*.32,p.y-bh-5*p.scale);c.lineTo(p.x+bw*.48,p.y-bh-5*p.scale);c.lineTo(p.x+bw/2,p.y-bh);c.fill();if(p.scale>.55){c.fillStyle="#97a7ae";const rows=Math.min(5,Math.max(1,Math.round(o.height/6)));for(let r=0;r<rows;r++){for(let col=0;col<2;col++){const ww=Math.max(2,3*p.scale),wh=Math.max(2,2.5*p.scale),wx=p.x-bw*.22+col*bw*.28,wy=p.y-bh+bh*(r+1)/(rows+1);c.fillRect(wx,wy,ww,wh)}}}}else if(o.kind==="tree"){const th=clamp(18*p.scale,6,45);c.strokeStyle="#2f3b34";c.lineWidth=Math.max(1,2*p.scale);c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x,p.y-th*.55);c.stroke();c.fillStyle="#3e5b49";c.beginPath();c.arc(p.x,p.y-th*.72,Math.max(3,8*p.scale),0,Math.PI*2);c.fill()}else if(o.kind==="lamp"){const lh=clamp(26*p.scale,8,58);c.strokeStyle="#748087";c.lineWidth=Math.max(1,1.5*p.scale);c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x,p.y-lh);c.stroke();c.fillStyle="#dbe2c1";c.beginPath();c.arc(p.x,p.y-lh,Math.max(1.5,2.5*p.scale),0,Math.PI*2);c.fill()}else if(o.kind==="poi"){const size=clamp(7*p.scale,3,15);c.fillStyle="#dbe5ea";c.fillRect(p.x-size/2,p.y-size,size,size);if(o.name&&p.scale>.55&&labels<4){c.fillStyle="#fff";c.font=`800 ${clamp(8*p.scale,7,11)}px -apple-system,Arial`;c.textAlign="center";c.fillText(o.name.slice(0,18),p.x,p.y-size-3);labels++}}}}
function drawJunctionGeometry(c,w,h,hz,d){if(!Number.isFinite(d.distance)||d.distance>130||d.arrived)return;const f=clamp(1-d.distance/150,0,1),y=hz+(h-hz)*(.12+.50*Math.pow(f,1.35)),th=clamp(10+f*40,10,55);c.fillStyle="#1a1e20";c.fillRect(0,y-th/2,w,th);c.strokeStyle="#d7dde0";c.lineWidth=1.5;c.beginPath();c.moveTo(0,y-th/2);c.lineTo(w,y-th/2);c.moveTo(0,y+th/2);c.lineTo(w,y+th/2);c.stroke();if(d.turn==="roundabout"){c.strokeStyle="#d7dde0";c.lineWidth=3;c.beginPath();c.arc(w/2,y,clamp(10+f*20,10,28),0,Math.PI*2);c.stroke();c.fillStyle="#2d393f";c.beginPath();c.arc(w/2,y,clamp(5+f*11,5,15),0,Math.PI*2);c.fill()}else if(d.turn==="left"||d.turn==="right"){c.fillStyle="rgba(255,255,255,.10)";const dir=d.turn==="right"?1:-1;c.beginPath();c.moveTo(w/2,y);c.lineTo(w/2+dir*w*.34,y-th*.35);c.lineTo(w/2+dir*w*.36,y+th*.35);c.closePath();c.fill()}}
function draw3D(d={}){const cv=$("drive"),r=cv.getBoundingClientRect(),D=devicePixelRatio||1,w=Math.max(1,r.width),h=Math.max(1,r.height);cv.width=Math.round(w*D);cv.height=Math.round(h*D);const c=cv.getContext("2d");c.setTransform(D,0,0,D,0,0);const hz=h*.30,cx=w/2,bot=h*1.04,rt=w*.28,rb=w*.94,total=Math.max(1,d.total||3),rec=clamp(d.recommended||2,1,total);const g=c.createLinearGradient(0,0,0,hz);g.addColorStop(0,"#0f1c24");g.addColorStop(1,"#263640");c.fillStyle=g;c.fillRect(0,0,w,hz);c.fillStyle="#2a343a";c.fillRect(0,hz,w,h-hz);const roadHeading=S.lastMatch&&S.gps?(travelDirection(S.lastMatch,S.gps)==="forward"?S.lastMatch.roadBearing:(S.lastMatch.roadBearing+180)%360):(S.heading||0),envHeading=S.demo?0:(S.gps?.speedMps>1.5&&Number.isFinite(S.heading)?S.heading:roadHeading);drawEnvironment(c,w,h,hz,envHeading);poly(c,[[cx-rt*.70,hz],[cx-rt*.50,hz],[cx-rb*.56,bot],[cx-rb*.70,bot]],"#565f63");poly(c,[[cx+rt*.50,hz],[cx+rt*.70,hz],[cx+rb*.70,bot],[cx+rb*.56,bot]],"#565f63");poly(c,[[cx-rt/2,hz],[cx+rt/2,hz],[cx+rb/2,bot],[cx-rb/2,bot]],"#15191c");line(c,[[cx-rt/2,hz],[cx-rb/2,bot]],"#e7ecee",2);line(c,[[cx+rt/2,hz],[cx+rb/2,bot]],"#e7ecee",2);drawJunctionGeometry(c,w,h,hz,d);c.globalAlpha=.2;poly(c,[[cx-rt/2+rt*(rec-1)/total,hz],[cx-rt/2+rt*rec/total,hz],[cx-rb/2+rb*rec/total,bot],[cx-rb/2+rb*(rec-1)/total,bot]],"#38e88c");c.globalAlpha=1;for(let i=1;i<total;i++){const xt=cx-rt/2+rt*i/total,xb=cx-rb/2+rb*i/total;for(let j=0;j<8;j++){const a=j/8,b=(j+.45)/8,ya=hz+(bot-hz)*a*a,yb=hz+(bot-hz)*b*b;line(c,[[xt+(xb-xt)*a*a,ya],[xt+(xb-xt)*b*b,yb]],"#d9dfe2",2)}}for(let i=1;i<=total;i++)arrow(c,cx-rb/2+rb*(i-.5)/total,h*.66,i===rec,d.turn||"through");if(d.distance){c.fillStyle="#fff";c.font="900 12px -apple-system,Arial";c.textAlign="center";c.fillText(`${Math.round(d.distance)} m`,cx,h*.47)}if(d.demo){c.fillStyle="#090b0d";c.fillRect(cx-10,hz-50,20,52);c.fillStyle="#ef5050";c.beginPath();c.arc(cx,hz-39,6,0,Math.PI*2);c.fill();c.fillStyle="#fff";c.font="900 11px -apple-system,Arial";c.textAlign="center";c.fillText(`${Math.ceil(d.signal)}s*`,cx,hz+22)}else if(d.signal){c.fillStyle="#090b0d";c.fillRect(cx-8,hz-42,16,42);c.fillStyle="#59666d";for(let i=0;i<3;i++){c.beginPath();c.arc(cx,hz-33+i*13,4,0,Math.PI*2);c.fill()}}}
function bind(){$("mapBtn").onclick=()=>setView("map");$("driveBtn").onclick=()=>setView("drive");$("gpsBtn").onclick=startGps;$("visionBtn").onclick=toggleVision;$("demoBtn").onclick=startDemo;$("allowGps").onclick=startGps;$("later").onclick=()=>$("permission")?.remove();$("closeVision").onclick=closeVision;$("clearRoute").onclick=clearRoute;$("streetRef").onclick=openStreetReference;window.addEventListener("resize",()=>{if(S.view==="drive")draw3D({lane:S.lastLane?.index||2,total:S.lastLane?.total||3,recommended:S.lastNav?recommendedLane(S.lastLane,S.lastNav.turn)||(S.lastLane?.index||2):(S.lastLane?.index||2),turn:S.lastNav?.turn||"through",distance:S.lastNav?.distance,signal:S.gps?relevantSignal(S.gps,S.lastMatch):null})})}
async function boot(){bind();initMap();setView("map");setStatus("BETA 6.1 · carte prête · active le GPS");if("serviceWorker"in navigator)try{const regs=await navigator.serviceWorker.getRegistrations();for(const reg of regs){const url=reg.active?.scriptURL||reg.waiting?.scriptURL||reg.installing?.scriptURL||"";if(url&&!url.includes("v=6.1.0"))await reg.unregister()}if("caches"in window){for(const key of await caches.keys())if(key.startsWith("md-beta-")&&key!=="md-beta-6.1.0")await caches.delete(key)}await navigator.serviceWorker.register("./sw.js?v=6.1.0",{updateViaCache:"none"})}catch(e){}}
boot();
})();
