(()=>{"use strict";
const P={lat:43.2858,lon:5.4140},S={map:null,roads:[],signals:[],gps:null,user:null,acc:null,view:"map",demo:false,t:0,timer:null},$=id=>document.getElementById(id),rad=x=>x*Math.PI/180,clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function status(t){$("status").textContent=t}
function dist(a,b){const R=6371000,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(Math.max(0,1-q)))}
function bbox(lat,lon,km){km=km||1.5;const a=km/111,b=km/(111*Math.cos(rad(lat)));return (lat-a)+","+(lon-b)+","+(lat+a)+","+(lon+b)}
function init(){S.map=L.map("map",{zoomControl:false}).setView([P.lat,P.lon],15);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(S.map)}
async function load(lat,lon){status("Chargement des routes…");const q='[out:json][timeout:25];(way["highway"]["highway"!~"footway|path|steps|pedestrian|cycleway"]('+bbox(lat,lon)+');node["highway"="traffic_signals"]('+bbox(lat,lon)+'););out geom tags;';try{const r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"data="+encodeURIComponent(q)}),d=await r.json();S.roads=[];S.signals=[];for(const e of d.elements||[]){if(e.type==="way"&&e.geometry&&e.geometry.length>1)S.roads.push({tags:e.tags||{},c:e.geometry.map(p=>({lat:p.lat,lon:p.lon}))});if(e.type==="node"&&e.tags&&e.tags.highway==="traffic_signals")S.signals.push({lat:e.lat,lon:e.lon})}status(S.roads.length+" routes · "+S.signals.length+" feux")}catch(e){status("Données OSM indisponibles — GPS actif")}}
function seg(p,a,b){const mx=111320*Math.cos(rad(p.lat)),my=110540,px=(p.lon-a.lon)*mx,py=(p.lat-a.lat)*my,bx=(b.lon-a.lon)*mx,by=(b.lat-a.lat)*my,l=bx*bx+by*by,t=l?clamp((px*bx+py*by)/l,0,1):0;return{d:Math.hypot(px-bx*t,py-by*t)}}
function nearest(p){let best=null;for(const r of S.roads)for(let i=0;i<r.c.length-1;i++){const s=seg(p,r.c[i],r.c[i+1]);if(s.d<45&&(!best||s.d<best.d))best={r:r,d:s.d}}return best}
function update(p){$("speed").textContent=Math.round(p.speed*3.6);const m=nearest(p);if(!m){$("road").textContent="—";$("lane").textContent="—";$("conf").textContent="—";$("advice").textContent="Route à confirmer";return}const total=parseInt(m.r.tags.lanes||m.r.tags["lanes:forward"]||"0",10)||0,conf=clamp(Math.round(100-Math.min(m.d,40)*1.6-Math.min(p.accuracy||99,40)*2.4),0,100);$("road").textContent=m.r.tags.name||m.r.tags.ref||m.r.tags.highway||"Route";$("conf").textContent=conf+"%";$("lane").textContent=total?"?/"+total:"—";$("advice").textContent=total?"🟡 "+total+" VOIES · POSITION À CONFIRMER":"Voies non renseignées";$("instruction").textContent=$("road").textContent;$("detail").textContent="GPS ±"+Math.round(p.accuracy||0)+" m · voie exacte refusée si précision insuffisante";let bs=null;for(const s of S.signals){const d=dist(p,s);if(d<450&&(!bs||d<bs))bs=d}$("signal").textContent=bs?Math.round(bs)+" m":"—";draw({total:total||3,rec:2})}
function marker(p){const ll=[p.lat,p.lon];if(!S.user){const icon=L.divIcon({className:"",html:'<div class="user-dot"></div>',iconSize:[18,18],iconAnchor:[9,9]});S.user=L.marker(ll,{icon:icon}).addTo(S.map);S.acc=L.circle(ll,{radius:p.accuracy||10,weight:1,color:"#1d79ff",fillColor:"#1d79ff",fillOpacity:.08}).addTo(S.map)}else{S.user.setLatLng(ll);S.acc.setLatLng(ll).setRadius(p.accuracy||10)}S.map.setView(ll,17)}
function gps(){if(!navigator.geolocation){status("GPS indisponible");return}$("permission")&&$("permission").remove();$("gpsBtn").classList.add("active");navigator.geolocation.watchPosition(async x=>{const c=x.coords,p={lat:c.latitude,lon:c.longitude,speed:Math.max(0,c.speed||0),accuracy:c.accuracy||999};S.gps=p;marker(p);await load(p.lat,p.lon);update(p);status("GPS ±"+Math.round(p.accuracy)+" m")},e=>status("GPS : "+e.message),{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
function view(v){S.view=v;$("map").style.display=v==="map"?"block":"none";$("drive").style.display=v==="drive"?"block":"none";$("car").style.display=v==="drive"?"block":"none";$("mapBtn").classList.toggle("active",v==="map");$("driveBtn").classList.toggle("active",v==="drive");$("modeLabel").textContent="BETA 2 · "+(v==="map"?"CARTE":"NAVIGATION 3D");if(v==="map")setTimeout(()=>S.map.invalidateSize(),50);else draw({total:3,rec:2})}
function demo(){if(S.demo){S.demo=false;clearInterval(S.timer);$("demoBtn").textContent="▶ Démo";status("Démo arrêtée");return}S.demo=true;S.t=0;view("drive");$("demoBtn").textContent="⏸ Démo";status("MODE DÉMO — données simulées");S.timer=setInterval(()=>{S.t+=.1;if(S.t>20)S.t=0;const change=S.t>6&&S.t<13,lane=S.t>13?3:2,rec=change?3:lane,signal=18-(S.t%18),distance=Math.max(0,350-S.t*14);$("speed").textContent=48;$("lane").textContent=lane+"/3";$("conf").textContent="96%";$("road").textContent="Avenue pilote";$("signal").textContent=Math.ceil(signal)+" s*";$("instruction").textContent=change?"Change de voie":S.t>6?"Tourne à droite":"Continue tout droit";$("detail").textContent="Dans "+Math.round(distance)+" m · feu SIMULÉ";$("advice").textContent=rec===lane?"🟢 RESTE VOIE "+lane+"/3":"➡️ REJOINS VOIE "+rec+"/3";draw({total:3,rec:rec,signal:signal,demo:true})},100)}
function poly(c,p,f){c.beginPath();p.forEach((x,i)=>i?c.lineTo(x[0],x[1]):c.moveTo(x[0],x[1]));c.closePath();c.fillStyle=f;c.fill()}
function draw(d){const cv=$("drive"),r=cv.getBoundingClientRect(),D=devicePixelRatio||1,w=r.width,h=r.height;cv.width=w*D;cv.height=h*D;const c=cv.getContext("2d");c.setTransform(D,0,0,D,0,0);const hz=h*.3,cx=w/2,bot=h*1.05,rt=w*.28,rb=w*.92,total=d.total||3,rec=d.rec||2;c.fillStyle="#18242b";c.fillRect(0,0,w,hz);c.fillStyle="#29343a";c.fillRect(0,hz,w,h-hz);poly(c,[[cx-rt/2,hz],[cx+rt/2,hz],[cx+rb/2,bot],[cx-rb/2,bot]],"#15191c");c.globalAlpha=.18;poly(c,[[cx-rt/2+rt*(rec-1)/total,hz],[cx-rt/2+rt*rec/total,hz],[cx-rb/2+rb*rec/total,bot],[cx-rb/2+rb*(rec-1)/total,bot]],"#32e884");c.globalAlpha=1;for(let i=1;i<total;i++){const xt=cx-rt/2+rt*i/total,xb=cx-rb/2+rb*i/total;c.strokeStyle="#d8dde0";c.lineWidth=2;c.beginPath();c.moveTo(xt,hz);c.lineTo(xb,bot);c.stroke()}if(d.demo){c.fillStyle="#090b0d";c.fillRect(cx-9,hz-46,18,46);c.fillStyle="#ec4e4e";c.beginPath();c.arc(cx,hz-36,5,0,Math.PI*2);c.fill();c.fillStyle="#fff";c.font="900 11px -apple-system";c.textAlign="center";c.fillText(Math.ceil(d.signal)+"s*",cx,hz+18)}}
function bind(){$("mapBtn").onclick=()=>view("map");$("driveBtn").onclick=()=>view("drive");$("gpsBtn").onclick=gps;$("allowGps").onclick=gps;$("later").onclick=()=>{$("permission")&&$("permission").remove()};$("demoBtn").onclick=demo}
async function boot(){bind();init();view("map");status("Carte prête · active le GPS");await load(P.lat,P.lon);if("serviceWorker"in navigator)try{await navigator.serviceWorker.register("./sw.js?v=2.0.1")}catch(e){}}
boot()})();